export const DIAGRAM_DESIGN = {
  typography: {
    family: 'Inter, -apple-system, BlinkMacSystemFont, Segoe UI, sans-serif',
    nodeWeight: 640,
    textWeight: 500,
    titleWeight: 720,
  },
  shape: {
    blockRadius: 7,
    nodeTextWidth: 0.86,
    nodeTextHeight: 0.76,
    chevronTextInset: 42,
    chevronTextHeight: 0.72,
  },
  title: {
    fontSize: { S: 32, M: 42, L: 58 },
    spacing: { S: 54, M: 72, L: 104 },
  },
  edge: {
    solidWidth: 2.8,
    dashedWidth: 2.5,
    solidOpacity: 0.95,
    dashedOpacity: 0.9,
    dashedPattern: '7, 7',
    logicalOpacity: 0.35,
    labelFontSize: 14,
    labelWeight: 680,
    labelCharWidth: 7.9,
    labelHaloWidth: 5,
    labelOffsetY: -9,
  },
  overlay: {
    groupStrokeWidth: 1.6,
    groupDash: '8, 8',
    groupOpacity: 0.45,
    groupLabelSize: 16,
    groupLabelWeight: 650,
    groupLabelOpacity: 0.78,
    sequenceLabelSize: 14,
    sequenceFillOpacity: 0.035,
  },
  legend: {
    radius: 8,
    opacity: 0.96,
    textWeight: 560,
    swatchRadius: 3,
  },
  paper: {
    titleGapScale: 0.82,
    titleTopInsetScale: 0.85,
  },
};
